### ISSUE TITLE
Assignment 3 draft

### ISSUE THREAD

**Issue by gianinayumul** [VIS-2129-F2020/gyumul-vis#2]
Error "breaks and labels do not match" in lines 159-162, 180-183. Thank you in advance for your help!

**Comment by traemalcolm** [comment]
It looks like all of your problems were stemming from you using the function length() instead of lengths() within the mutate function. I went ahead and changed that in your code, and pushed it to your repo and you should see a short comment from me in the markdown file from me when you pull and update your file.
